# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "terraform-state"
    key                  = "subscriptions/Azure subscription 1/resource-groups/terra-v2/buckets/k8s-ws-bkt/terraform.tfstate"
    resource_group_name  = "terraform-state"
    storage_account_name = "k8spracticestorage"
    subscription_id      = "61f82aeb-5c08-4a8c-9989-6b3b9626036b"
  }
}
